### PR TITLE
Install ruby-augeas from RubyGems on Debian for Ruby >= 2.0.0

### PR DESCRIPTION
**Pull request by todd**
Re: discussion from opentable/puppet-homes#7

### CODE REVIEW

**Comment by todd** [comment]
cc @liamjbennett @stevenschlansker @fessyfoo

**Comment by stevenschlansker** [comment]
Nice

**Comment by todd** [comment]
I spent a bunch of time trying to fix 1.8.7 builds on Travis, but there's some terrible dependency hell stuff going on there that's probably out of scope for this PR.

**Comment by todd** [comment]
:heart: Can we cut a new version with this fix and push it to the forge?

**Pull request merged**
